# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rKp3_ZQrtg_pbQ588e75az70e2NhcFVC
"""

import pandas as pd
import numpy as np

# Загрузка данных
df = pd.read_csv('ecommerce_sales_2025.csv')

# 1. Первичный обзор
print(df.shape)
print(df.info())
print(df.isnull().sum())

# 2. Проверка дубликатов
duplicates = df.duplicated(subset=['order_id']).sum()
print(f'Дубликатов order_id: {duplicates}')

# 3. Проверка выбросов
# Отрицательная выручка не может быть
df = df[df['revenue'] >= 0]

# Проверка количества товаров (должно быть >0)
df = df[df['quantity'] > 0]

# 4. Проверка диапазонов
# rating от 1 до 5
df = df[(df['customer_rating'] >= 1) & (df['customer_rating'] <= 5)]

# discount_percent от 0 до 100
df = df[(df['discount_percent'] >= 0) & (df['discount_percent'] <= 100)]

# 5. Создание новых полезных полей
df['order_year'] = pd.DatetimeIndex(df['order_date']).year
df['order_month'] = pd.DatetimeIndex(df['order_date']).month
df['profit_margin'] = df['revenue'] * (1 - df['discount_percent']/100)  # упрощённо

# 6. Сохранение очищенного файла
df.to_csv('ecommerce_sales_cleaned.csv', index=False)
print(f'Финальный размер: {df.shape}')